stages:
  - build
  - lint
  - test

default:
  image: node:18-alpine

build:
  stage: build
  script:
    - cd server && npm ci
  artifacts:
    paths:
      - server/node_modules/
    expire_in: 1 hour

lint:back:
  stage: lint
  needs:
    - job: build
      artifacts: true
  script:
    - cd server && npm run lint:back

lint:front:
  stage: lint
  needs:
    - job: build
      artifacts: true
  script:
    - cd server && npm run lint:front

test:unit:
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - cd server && npm test
